# Generated by Django 2.0 on 2018-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0002_auto_20171228_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='pic',
            field=models.ImageField(default='static/brainstorm/images/img1.jpg', upload_to='static/brainstorm/images/'),
        ),
    ]
