# Generated by Django 2.0 on 2018-01-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0003_level_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ans',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='level',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
