# Generated by Django 2.0 on 2018-01-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0004_auto_20180105_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
