# Generated by Django 2.0 on 2018-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0005_auto_20180105_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='pic',
            field=models.FilePathField(blank=True, path='https://brainstorm2k18.herokuapp.com/static/brainstorm/images'),
        ),
    ]
