# Generated by Django 2.0 on 2018-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0006_auto_20180105_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='pic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
